carris_dbt:
  outputs:
    dev:
      dataset: raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/patricia-oliveira/gcp_keys/service_account_key.json
      location: EU
      method: service-account
      priority: interactive
      project: edit-445616
      threads: 1
      type: bigquery
  target: dev