carris_dbt:
  outputs:
    dev:
      dataset: raw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('SERVICE_ACCOUNT_FILE') }}"
      location: US
      method: service-account
      priority: interactive
      project: edit-445616
      threads: 1
      type: bigquery
  target: dev